-- Donnees de reference (villes, badges)
-- Aucune donnee utilisateur.

SET NAMES utf8mb4;

SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
LOCK TABLES `villes` WRITE;
INSERT INTO `villes` (`short_name`, `long_name`, `fr_ville`, `fr_pays`, `commentaire`) VALUES ('DHK','Dhaka','Dacca','Bangladesh',NULL),
('ANVR','Anvers','Anvers','Belgique',NULL),
('BXL','Bruxelles','Bruxelles','Belgique',NULL),
('CHAR','Charleroi','Charleroi','Belgique',NULL),
('RDU','Redu','Redu','Belgique',NULL),
('BT','Bhutan','Bhoutan','Bhoutan',NULL),
('POTI','Potosi','Potosí','Bolivie',NULL),
('GRU','Grude','Grude','Bosnie-Herzégovine',NULL),
('SP','São Paulo','São Paulo','Brésil',NULL),
('HK','Hong Kong','Hong Kong','Chine',NULL),
('DJN','Daejeon','Daejeon','Corée du Sud',NULL),
('BRC','Barcelona','Barcelone','Espagne',NULL),
('BBO','Bilbao','Bilbao','Espagne',NULL),
('MLGA','Málaga','Malaga','Espagne',NULL),
('MEN','Menorca','Minorque','Espagne',NULL),
('LA','Los Angeles','Los Angeles','États-Unis',NULL),
('MIA','Miami','Miami','États-Unis',NULL),
('NY','New York','New York','États-Unis',NULL),
('SD','San Diego','San Diego','États-Unis',NULL),
('AIX','Aix-en-Provence','Aix-en-Provence','France',NULL),
('AVI','Avignon','Avignon','France',NULL),
('BTA','Bastia','Bastia','France',NULL),
('CAPF','Cap Ferret','Le Cap Ferret','France',NULL),
('CLR','Clermont-Ferrand','Clermont-Ferrand','France',NULL),
('CON','Contis-Les-Bains','Contis-Les-Bains','France',NULL),
('CAZ','Côte d Azur','Côte d\'Azur','France',NULL),
('DIJ','Dijon','Dijon','France',NULL),
('FTBL','Fontainebleau','Fontainebleau','France',NULL),
('FRQ','Forcalquier','Forcalquier','France',NULL),
('GRN','Grenoble','Grenoble','France',NULL),
('LCT','La Ciotat','La Ciotat','France',NULL),
('REUN','La Réunion','La Réunion','France',NULL),
('LIL','Lille','Lille','France',NULL),
('LBR','Luberon','Lubéron','France',NULL),
('LY','Lyon','Lyon','France',NULL),
('MARS','Marseille','Marseille','France',NULL),
('MTB','Montauban','Montauban','France',NULL),
('MPL','Montpellier','Montpellier','France',NULL),
('NA','Nantes','Nantes','France',NULL),
('NIM','Nîmes','Nîmes','France',NULL),
('PA','Paris','Paris','France',NULL),
('PAU','Pau','Pau','France',NULL),
('PRP','Perpignan','Perpignan','France',NULL),
('RN','Rennes','Rennes','France',NULL),
('TLS','Toulouse','Toulouse','France',NULL),
('VLMO','Valmorel','Valmorel','France',NULL),
('VRS','Versailles','Versailles','France',NULL),
('LDN','London','Londres','Royaume-Uni',NULL),
('MAN','Manchester','Manchester','Royaume-Uni',NULL),
('NCL','Newcastle','Newcastle','Royaume-Uni',NULL),
('VRN','Varanasi','Varanasi','Inde',NULL),
('ELT','Eilat','Eilat','Israël',NULL),
('RA','Ravenna','Ravenne','Italie',NULL),
('ROM','Roma','Rome','Italie',NULL),
('TK','Tokyo','Tokyo','Japon',NULL),
('MBSA','Mombasa','Mombasa','Kenya',NULL),
('MRAK','Marrakech','Marrakech','Maroc',NULL),
('RBA','Rabat','Rabat','Maroc',NULL),
('CCU','Cancún','Cancún','Mexique',NULL),
('KAT','Katmandou','Katmandou','Népal',NULL),
('AMS','Amsterdam','Amsterdam','Pays-Bas',NULL),
('NOO','Noordwijk','Noordwijk','Pays-Bas',NULL),
('RTD','Rotterdam','Rotterdam','Pays-Bas',NULL),
('FAO','Faro','Faro','Portugal',NULL),
('LJU','Ljubljana','Ljubljana','Slovénie',NULL),
('HALM','Halmstad','Halmstad','Suède',NULL),
('VSB','Visby','Visby','Suède',NULL),
('ANZR','Anzère','Anzère','Suisse',NULL),
('BSL','Basel','Bâle','Suisse',NULL),
('BRN','Bern','Berne','Suisse',NULL),
('GNV','Genève','Genève','Suisse',NULL),
('LSN','Lausanne','Lausanne','Suisse',NULL),
('GRTI','Grumeti','Grumeti','Tanzanie',NULL),
('BGK','Bangkok','Bangkok','Thaïlande',NULL),
('DJBA','Djerba','Djerba','Tunisie',NULL),
('IST','Istanbul','Istanbul','Turquie',NULL),
('BRL','Berlin','Berlin','Allemagne',NULL),
('KLN','Köln','Cologne','Allemagne',NULL),
('FKF','Frankfurt','Francfort','Allemagne',NULL),
('MUN','München','Munich','Allemagne',NULL),
('PRT','Perth','Perth','Australie',NULL),
('WN','Wien','Vienne','Autriche',NULL),
('MLB','Merbourne','Melbourne','Australie',NULL),
('SL','Séoul','Séoul','Corée',NULL),
('BAB','Bayonne-Anglet-Biarritz','Bayonne-Anglet-Biarritz','France',NULL),
('ORLN','Orléans','Orléans','France',NULL),
('STK','Stockholm','Stockholm','Suède',NULL),
('AMI','Amiens','Amiens','France',NULL);
UNLOCK TABLES;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
SET @OLD_AUTOCOMMIT=@@AUTOCOMMIT, @@AUTOCOMMIT=0;
LOCK TABLES `badges` WRITE;
INSERT INTO `badges` (`id_badge`, `nom_badge`, `description`, `icone`, `date_creation`, `fonction`, `arguments`, `actif`, `niveau`) VALUES (1,'Avant-Gardiste','<div class=\'message\'>Vous étiez parmi les premiers à explorer cet univers, présent avant l\'ouverture au public. Un vrai pionnier du flash !</div> <div=\'deblo\'>Présent avant l\'ouverture au public</div>','🚀','2025-04-26 17:44:24',NULL,NULL,0,'Gold'),
(2,'Premier Flash','<div class=\'message\'>Votre aventure commence ! Vous avez réussi votre premier flash. Bienvenue dans le monde des collectionneurs de pixels !</div><div=\'deblo\'>Au moins 1 invader flashé</div>','📸','2025-04-27 14:40:14','check_badge_nbr_flash','1',1,'Standard'),
(3,'Début Prometteur','<div class=\'message\'>Dix flashs réussis ! Vous prenez le coup de main et montrez déjà une belle curiosité. Continuez sur cette lancée !</div><div=\'deblo\'>Au moins 10 invader flashé</div>','✨','2025-04-27 14:40:42','check_badge_nbr_flash','10',1,'Standard'),
(4,'Collectionneur Attentif','<div class=\'message\'>Cinquante flashs au compteur ! Votre collection s\'étoffe et votre œil s\'aiguise pour repérer les Invaders.</div><div=\'deblo\'>Au moins 50 invader flashé</div>','🔥','2025-04-27 14:41:30','check_badge_nbr_flash','50',1,'Standard'),
(5,'Première centaine','<div class=\'message\'>Une centaine d\'Invaders flashés ! C\'est une étape marquante. Votre galerie personnelle prend de l\'ampleur.</div><div=\'deblo\'>Au moins 100 invaders flashés</div>','💯','2025-04-27 14:41:57','check_badge_nbr_flash','100',1,'Standard'),
(6,'Le Flasheur Assidu','<div class=\'message\'>Avec 150 flashs, votre persévérance est évidente. Chaque Invader est une trouvaille, et vous ne manquez pas une occasion</div><div=\'deblo\'>Au moins 150 invaders flashés</div>','📚','2025-04-27 14:42:04','check_badge_nbr_flash','150',1,'Bronze'),
(7,'L\'Expert','<div class=\'message\'>Impressionnant ! 250 Invaders flashés. Vous maîtrisez l\'art du flash et votre collection devient une référence.</div><div=\'deblo\'>Au moins 250 invaders flashés</div>','🌟','2025-04-27 14:42:48','check_badge_nbr_flash','250',1,'Bronze'),
(8,'Le Maître','<div class=\'message\'>Whoa, 500 Invaders capturés par votre flash ! Votre passion pour la collection est indéniable et votre tableau de chasse impressionnant </div><div=\'deblo\'>Au moins 500 invaders flashés</div>','💫','2025-04-27 14:42:56','check_badge_nbr_flash','500',1,'Silver'),
(9,'Le Virtuose','<div class=\'message\'>750 flashs ! Vous êtes aux portes de l\'excellence. Le millier est en vue, continuez votre incroyable quête de découvertes ! </div><div=\'deblo\'>Au moins 750 invaders flashés</div>','🌠','2025-04-27 14:43:02','check_badge_nbr_flash','750',1,'Silver'),
(10,'Le Collectionneur Légendaire','<div class=\'message\'>Mille Invaders flashés ! Vous êtes officiellement un Collectionneur Légendaire. Votre nom est synonyme de passion et de découverte. </div><div=\'deblo\'>Au moins 1000 invaders flashés</div>','🏆','2025-04-27 14:43:07','check_badge_nbr_flash','1000',1,'Silver'),
(11,'L\'Archiviste','<div class=\'message\'>1500 Invaders ! Votre collection est digne d\'un musée. Vous ne jouez plus dans la même catégorie, vous êtes un archiviste de renom.</div><div=\'deblo\'>Au moins 1500 invaders flashés</div>','🏅','2025-04-27 14:44:01','check_badge_nbr_flash','1500',1,'Gold'),
(12,'La Légende','<div class=\'message\'>Incroyable, 2000 Invaders flashés ! Est-ce seulement possible ? Vous avez redéfini l\'art de la collection.</div><div=\'deblo\'>Au moins 2000 invaders flashés</div>','🌌','2025-04-27 14:44:57','check_badge_nbr_flash','2000',1,'Gold'),
(13,'Le G.O.A.T.','<div class=\'message\'>The GOAT, comme disait mon grand-père</div><div=\'deblo\'>Au moins 2500 invaders flashés</div>','🐐','2025-04-27 14:49:52','check_badge_nbr_flash','2500',1,'Gold'),
(14,'Grand Voyageur','<div class=\'message\'>Un vrai explorateur ! Au moins 1000 km séparent vos deux flashs les plus éloignés. Vous aimez découvrir des Invaders aux quatre coins du monde.</div><div=\'deblo\'>Au moins 1000 km entre vos deux flashs les plus éloignés</div>','🌍','2025-04-27 15:10:24','check_badge_distance','1000',1,'Bronze'),
(15,'Nomade Intercontinental','<div class=\'message\'>Invader Traveller ! Votre quête de flashs vous a mené sur plus de 2000 km. Le monde est votre terrain de chasse.</div><div=\'deblo\'>Au moins 2000 km entre vos deux flashs les plus éloignés</div>','✈️','2025-04-27 15:10:24','check_badge_distance','2000',1,'Silver'),
(16,'Globe-Flasheur Ultime','<div class=\'message\'>Jusqu\'au bout du monde ! Plus de 3000 km entre deux de vos prises. Votre passion pour le flash est sans frontières.</div><div=\'deblo\'>Au moins 3000 km entre vos deux flashs les plus éloignés</div>','🗺️','2025-04-27 15:10:24','check_badge_distance','3000',1,'Gold'),
(17,'Space Oddity','<div class=\'message\'>Major Tom à Ground Control... Vous avez flashé l\'ISS (SPACE_1) ! Un spécimen rare et une prise véritablement cosmique pour votre collection.</div><div=\'deblo\'>Flasher SPACE_1</div>','🛰️','2025-04-27 15:15:41','check_badge_specific_flash','\'ISS_1\'',1,'Gold'),
(18,'Oiseau de nuit','<div class=\'message\'>Les Invaders nocturnes ne vous échappent pas !</div><div=\'deblo\'>Flasher 30 Invaders entre 22h et 6h du matin.</div>','🦉','2025-05-08 15:24:16','check_badge_flashnuit','30',1,'Silver'),
(19,'Explorateur Urbain','<div class=\'message\'>Les villes n\'ont plus de secrets pour vous ! Vous avez flashé des Invaders dans 5 villes différentes. Votre carte du monde s\'illumine !</div><div=\'deblo\'>Flasher des Invaders dans 5 villes différentes.</div>','🏙️','2025-05-08 15:26:42','check_badge_nbr_ville','5',1,'Silver'),
(20,'Ambassadeur','<div class=\'message\'>De métropole en métropole ! Vous avez flashé des Invaders dans 5 pays différents ! Un véritable ambassadeur du flash !</div><div=\'deblo\'>Flasher des Invaders dans 5 pays différents.</div>','🏛️','2025-05-08 15:28:00','check_badge_nbr_pays','5',1,'Gold'),
(21,'La sortie du weekend','<div class=\'message\'>3 jours de Flash consécutifs ! C\'est une passion ?</div><div=\'deblo\'>Flasher des Invaders pendant 3 jours d\'affilée..</div>','🗓️','2025-05-08 16:02:15','check_badge_nbr_jours_consecutifs','3',1,'Bronze'),
(22,'Quotidien','<div class=\'message\'>5 jours de Flash consécutifs ! C\'est votre travail ?</div><div=\'deblo\'>Flasher des Invaders pendant 5 jours d\'affilée..</div>','🏭','2025-05-08 16:02:56','check_badge_nbr_jours_consecutifs','5',1,'Silver'),
(23,'7 Jours de Flash','<div class=\'message\'>7 jours de Flash consécutifs ! C\'est votre vie maintenant.</div><div=\'deblo\'>Flasher des Invaders pendant 7 jours d\'affilée.</div>','🧬','2025-05-08 16:03:02','check_badge_nbr_jours_consecutifs','7',1,'Gold');
UNLOCK TABLES;
COMMIT;
SET AUTOCOMMIT=@OLD_AUTOCOMMIT;
